moved things around
running into errors trying to use environment variables:

$ slackcli ohai7
Traceback (most recent call last):
  File "/usr/local/bin/slackcli", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/slackcli.py", line 46, in main
    SLACK_TOKEN = args.token or SLACK_TOKEN
UnboundLocalError: local variable 'SLACK_TOKEN' referenced before assignment

Since the /usr/local/bin/slackcli that setup.py creates only imports main (from slackcli import main) from slackcli.py, the SLACK_* variables don't get initialized. Moving the SLACK_* definitions and send_text inside main() solves this issue.  If there's a way to make setup.py include * from slackcli, that would solve it, too, but I'm not familiar with that, so I did this :)